In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\raw\data_hotel_bookings.csv"
)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
df.shape

(119390, 32)

In [4]:
df.isnull().sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
hotel                                  0
previous_cancellations                 0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
previous_bookings_not_canceled         0
is_repeated_guest                      0
is_canceled                            0
distribution_channel                   0
market_segment                         0
meal                                   0
babies                                 0
adults                                 0
stays_in_week_nights                   0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
arrival_date_week_number               0
arrival_date_month                     0
arrival_date_year                      0
lead_time                              0
reservation_status_date                0
dtype: int64

## Missing Value Analysis

Columns containing missing values:
- company
- agent
- country
- children

In [5]:
missing_percent = (df.isnull().sum()/len(df))*100

missing_percent.sort_values(ascending=False)

company                           94.306893
agent                             13.686238
country                            0.408744
children                           0.003350
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
hotel                              0.000000
previous_cancellations             0.000000
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
previous_bookings_not_canceled     0.000000
is_repeated_guest                  0.000000
is_canceled                        0.000000
distribution_channel               0.000000
market_segment                     0.000000
meal                               0.000000
babies                             0.000000
adults                             0.000000
stays_in_week_nights               0.000000
stays_in_weekend_nights            0.000000
arrival_date_day_of_month          0.000000
arrival_date_week_number           0.000000
arrival_date_month                 0.000000
arrival_date_year                  0.000000
lead_time                          0.000000
reservation_status_date            0.000000
dtype: float64

In [6]:
df.drop('company', axis=1, inplace=True)

In [7]:
df.shape

(119390, 31)

In [8]:
df['agent'] = df['agent'].fillna(0)

In [9]:
df['agent'].isnull().sum()

np.int64(0)

In [10]:
df['country'].mode()[0]

'PRT'

In [11]:
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [12]:
df['country'].isnull().sum()

np.int64(0)

In [13]:
df['children'] = df['children'].fillna(df['children'].median())

In [14]:
df['children'].isnull().sum()

np.int64(0)

In [15]:
df.isnull().sum().sort_values(ascending=False).head()

hotel                          0
is_repeated_guest              0
reservation_status             0
total_of_special_requests      0
required_car_parking_spaces    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(32020)

In [17]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 32020

In [18]:
df = df.drop_duplicates()

In [19]:
df.shape

(87370, 31)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87370 entries, 0 to 119389
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87370 non-null  object
 1   is_canceled                     87370 non-null  int64
 2   lead_time                       87370 non-null  int64
 3   arrival_date_year               87370 non-null  int64
 4   arrival_date_month              87370 non-null  object
 5   arrival_date_week_number        87370 non-null  int64
 6   arrival_date_day_of_month       87370 non-null  int64
 7   stays_in_weekend_nights         87370 non-null  int64
 8   stays_in_week_nights            87370 non-null  int64
 9   adults                          87370 non-null  int64
 10  children                        87370 non-null  float64
 11  babies                          87370 non-null  int64
 12  meal                            87370 non-null  object
 13  country                         87370 non-null  object
 14  market_segment                  87370 non-null  object
 15  distribution_channel            87370 non-null  object
 16  is_repeated_guest               87370 non-null  int64
 17  previous_cancellations          87370 non-null  int64
 18  previous_bookings_not_canceled  87370 non-null  int64
 19  reserved_room_type              87370 non-null  object
 20  assigned_room_type              87370 non-null  object
 21  booking_changes                 87370 non-null  int64
 22  deposit_type                    87370 non-null  object
 23  agent                           87370 non-null  float64
 24  days_in_waiting_list            87370 non-null  int64
 25  customer_type                   87370 non-null  object
 26  adr                             87370 non-null  float64
 27  required_car_parking_spaces     87370 non-null  int64
 28  total_of_special_requests       87370 non-null  int64
 29  reservation_status              87370 non-null  object
 30  reservation_status_date         87370 non-null  object
dtypes: float64(3), int64(16), object(12)
memory usage: 21.3+ MB

In [21]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000,87370.000000
mean,0.274969,79.911686,2016.210290,26.839533,15.815360,1.005448,2.625798,1.875953,0.138675,0.010828,0.039087,0.030422,0.184045,0.271672,81.011194,0.749788,106.346935,0.084251,0.698638
std,0.446501,86.056471,0.686116,13.673204,8.834842,1.031974,2.053692,0.626473,0.455933,0.113613,0.193802,0.369200,1.732148,0.727335,109.941520,10.017213,55.004259,0.281571,0.831946
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,11.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,72.000000,0.000000,0.000000
50%,0.000000,49.000000,2016.000000,27.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,98.100000,0.000000,0.000000
75%,1.000000,125.000000,2017.000000,37.000000,23.000000,2.000000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,0.000000,134.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,391.000000,5400.000000,8.000000,5.000000

In [22]:
df.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\cleaned\hotel_bookings_cleaned.csv",
    index=False
)

In [23]:
import os

os.listdir(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\cleaned"
)

['hotel_bookings_cleaned.csv']

# Day 2 Conclusion

Data cleaning was completed successfully.

Actions performed:
- Removed company column due to excessive missing values.
- Filled missing values in agent, country, and children columns.
- Removed duplicate records.
- Verified data types and dataset structure.
- Saved cleaned dataset for future analysis.

The cleaned dataset is now ready for Exploratory Data Analysis (EDA).