# Travel, Tourism & Hospitality
## Customer Retention and Dynamic Pricing Analysis

### Week 1 - Day 3

Feature Engineering

Dataset:
Hotel Booking Demand Dataset

Author:
Niveditha J

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\cleaned\hotel_bookings_cleaned.csv"
)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,0.0,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,0.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [3]:
df.shape

(87370, 31)

In [4]:
df['total_stay_nights'] = (
    df['stays_in_weekend_nights']
    + df['stays_in_week_nights']
)

df[['stays_in_weekend_nights',
    'stays_in_week_nights',
    'total_stay_nights']].head()

   stays_in_weekend_nights  stays_in_week_nights  total_stay_nights
0                        0                     0                  0
1                        0                     0                  0
2                        0                     1                  1
3                        0                     1                  1
4                        0                     2                  2

In [5]:
df['total_stay_nights'].describe()

count    87370.000000
mean         3.631246
std          2.763579
min          0.000000
25%          2.000000
50%          3.000000
75%          5.000000
max         69.000000
Name: total_stay_nights, dtype: float64

In [6]:
df['total_guests'] = (
    df['adults']
    + df['children']
    + df['babies']
)

df[['adults','children','babies','total_guests']].head()

   adults  children  babies  total_guests
0       2       0.0       0           2.0
1       2       0.0       0           2.0
2       1       0.0       0           1.0
3       1       0.0       0           1.0
4       2       0.0       0           2.0

In [7]:
df['total_guests'].describe()

count    87370.000000
mean         2.025455
std          0.794309
min          0.000000
25%          2.000000
50%          2.000000
75%          2.000000
max         55.000000
Name: total_guests, dtype: float64

In [8]:
df['booking_changed'] = np.where(
    df['booking_changes'] > 0,
    1,
    0
)

df['booking_changed'].value_counts()

booking_changed
0    71469
1    15901
Name: count, dtype: int64

In [9]:
df['has_previous_cancellation'] = np.where(
    df['previous_cancellations'] > 0,
    1,
    0
)

df['has_previous_cancellation'].value_counts()

has_previous_cancellation
0    85685
1     1685
Name: count, dtype: int64

In [10]:
df['special_request_flag'] = np.where(
    df['total_of_special_requests'] > 0,
    1,
    0
)

df['special_request_flag'].value_counts()

special_request_flag
0    43876
1    43494
Name: count, dtype: int64

In [11]:
df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'total_stay_nights',
       'total_guests', 'booking_changed', 'has_previous_cancellation',
       'special_request_flag'],
      dtype='object')

In [12]:
df.shape

(87370, 36)

Create folder:
             data/processed/

In [15]:
import os

os.makedirs(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed",
    exist_ok=True
)

In [16]:
df.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\hotel_bookings_feature_engineered.csv",
    index=False
)

In [17]:
import os

os.listdir(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed"
)

['hotel_bookings_feature_engineered.csv']