In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\hotel_bookings_selected_features.csv"
)

df.shape

(87359, 29)

In [3]:
df.head()

,hotel,lead_time,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,total_stay_nights,total_guests,booking_changed,has_previous_cancellation,special_request_flag,is_canceled
0,Resort Hotel,342,July,0,0,2,0.0,0,BB,PRT,...,Transient,0.0,0,0,0,2.0,1,0,0,0
1,Resort Hotel,737,July,0,0,2,0.0,0,BB,PRT,...,Transient,0.0,0,0,0,2.0,1,0,0,0
2,Resort Hotel,7,July,0,1,1,0.0,0,BB,GBR,...,Transient,75.0,0,0,1,1.0,0,0,0,0
3,Resort Hotel,13,July,0,1,1,0.0,0,BB,GBR,...,Transient,75.0,0,0,1,1.0,0,0,0,0
4,Resort Hotel,14,July,0,2,2,0.0,0,BB,GBR,...,Transient,98.0,0,1,2,2.0,0,0,1,0

## Data Preprocessing

Machine learning models require numerical input.

Categorical variables are converted into numeric values using Label Encoding.

In [4]:
categorical_columns = df.select_dtypes(include='object').columns

categorical_columns

Index(['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment',
       'distribution_channel', 'reserved_room_type', 'assigned_room_type',
       'deposit_type', 'customer_type'],
      dtype='object')

In [5]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

In [6]:
for column in categorical_columns:
    df[column] = encoder.fit_transform(df[column])

df.head()

,hotel,lead_time,arrival_date_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,total_stay_nights,total_guests,booking_changed,has_previous_cancellation,special_request_flag,is_canceled
0,1,342,5,0,0,2,0.0,0,0,135,...,2,0.0,0,0,0,2.0,1,0,0,0
1,1,737,5,0,0,2,0.0,0,0,135,...,2,0.0,0,0,0,2.0,1,0,0,0
2,1,7,5,0,1,1,0.0,0,0,59,...,2,75.0,0,0,1,1.0,0,0,0,0
3,1,13,5,0,1,1,0.0,0,0,59,...,2,75.0,0,0,1,1.0,0,0,0,0
4,1,14,5,0,2,2,0.0,0,0,59,...,2,98.0,0,1,2,2.0,0,0,1,0

In [7]:
df.dtypes

hotel                               int64
lead_time                           int64
arrival_date_month                  int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                                int64
country                             int64
market_segment                      int64
distribution_channel                int64
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                  int64
assigned_room_type                  int64
booking_changes                     int64
deposit_type                        int64
customer_type                       int64
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
total_stay_nights                   int64
total_guests                      float64
booking_changed                     int64
has_previous_cancellation           int64
special_request_flag                int64
is_canceled                         int64
dtype: object

In [8]:
df.isnull().sum().sum()

np.int64(0)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87359 entries, 0 to 87358
Data columns (total 29 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87359 non-null  int64
 1   lead_time                       87359 non-null  int64
 2   arrival_date_month              87359 non-null  int64
 3   stays_in_weekend_nights         87359 non-null  int64
 4   stays_in_week_nights            87359 non-null  int64
 5   adults                          87359 non-null  int64
 6   children                        87359 non-null  float64
 7   babies                          87359 non-null  int64
 8   meal                            87359 non-null  int64
 9   country                         87359 non-null  int64
 10  market_segment                  87359 non-null  int64
 11  distribution_channel            87359 non-null  int64
 12  is_repeated_guest               87359 non-null  int64
 13  previous_cancellations          87359 non-null  int64
 14  previous_bookings_not_canceled  87359 non-null  int64
 15  reserved_room_type              87359 non-null  int64
 16  assigned_room_type              87359 non-null  int64
 17  booking_changes                 87359 non-null  int64
 18  deposit_type                    87359 non-null  int64
 19  customer_type                   87359 non-null  int64
 20  adr                             87359 non-null  float64
 21  required_car_parking_spaces     87359 non-null  int64
 22  total_of_special_requests       87359 non-null  int64
 23  total_stay_nights               87359 non-null  int64
 24  total_guests                    87359 non-null  float64
 25  booking_changed                 87359 non-null  int64
 26  has_previous_cancellation       87359 non-null  int64
 27  special_request_flag            87359 non-null  int64
 28  is_canceled                     87359 non-null  int64
dtypes: float64(3), int64(26)
memory usage: 19.3 MB

## Encoding Summary

All categorical variables have been converted into numerical values.

The dataset is now compatible with machine learning algorithms.

In [10]:
df.to_csv(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed\hotel_bookings_encoded.csv",
    index=False
)

print("Encoded dataset saved successfully.")

Encoded dataset saved successfully.

In [11]:
import os

os.listdir(
    r"C:\Users\Hp\Desktop\Travel-Tourism-Customer-Retention-Analysis\data\processed"
)

['hotel_bookings_encoded.csv',
 'hotel_bookings_feature_engineered.csv',
 'hotel_bookings_final_cleaned.csv',
 'hotel_bookings_selected_features.csv',
 'hotel_bookings_validated.csv',
 'week1_completed_dataset.csv']

## Findings

- Identified all categorical variables.
- Converted categorical values into numerical labels.
- Verified that all columns are numeric.
- Confirmed there are no missing values.
- Saved the encoded dataset for machine learning.

## Day 2 Conclusion

The selected dataset was successfully preprocessed by encoding categorical features into numerical values.

All variables are now suitable for machine learning algorithms, and the processed dataset has been saved for model development.